[package]
name = "coinbase-rs"
version = "0.1.0"
authors = ["John Barker <dev@j16r.net>"]
edition = "2018"
description = "Coinbase client for Rust"
repository = "https://github.com/j16r/coinbase-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "api-bindings", "cryptography::cryptocurrencies" ]
keywords = [ "exchange", "coinbase", "bitcoin" ]

[dependencies]
base64 = "*"
bigdecimal = { version = "*", features = [ "serde" ] }
chrono = { version = "*", features = [ "serde" ] }
failure = "*"
hmac = "*"
hyper = "*"
hyper-tls = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha2 = "*"
tokio = "*"
uuid = { version = "*", features = [ "serde" ] }
