[package]
name = "coinbase-rs"
version = "0.3.0"
authors = ["John Barker <dev@j16r.net>"]
edition = "2018"
description = "Coinbase client for Rust"
repository = "https://github.com/j16r/coinbase-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "api-bindings", "cryptography::cryptocurrencies" ]
keywords = [ "exchange", "coinbase", "bitcoin" ]

[dependencies]
async-stream = "*"
base64 = "0.10"
bigdecimal = { version = "0.2", features = [ "serde" ] }
chrono = { version = "0.4", features = [ "serde" ] }
failure = "0.1"
futures = "0.3"
hmac = "0.7"
http = "*"
hyper = { version = "*", features = [ "full" ] }
hyper-tls = "*"
serde = "1.0"
serde_derive = "*"
serde_json = "*"
sha2 = "0.8"
thiserror = "1.0"
tokio = { version = "*", features = [ "full" ] }
tokio-stream = "*"
uritemplate = "0.1.2"
uuid = { version = "0.8.1", features = [ "serde", "v4" ] }
