[package]
name = "coinbase-rs"
version = "0.1.0"
authors = ["John Barker <dev@j16r.net>"]
edition = "2018"

[dependencies]
base64 = "0.10.0"
chrono = { version = "0.4.5", features = [ "serde" ] }
failure = "0.1.5"
hmac = "0.7.0"
hyper = "0.12.25"
hyper-tls = "0.3.2"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
sha2 = "0.8.0"
tokio = "0.1.18"
